[manifest]
id = "bardakoff_banjo"
version = "1.0.1"
display_name = "Bardakoff Banjo"
description = "Ce mod implémente le français PAL dans l'édition Recomp du jeu.\n\nThis mod brings PAL french in the recomp."
short_description = "Ce mod implémente le français PAL dans l'édition Recomp du jeu.\n\nThis mod brings PAL french in the recomp."
authors = [ "Lorsoen" ]
game_id = "bk"
minimum_recomp_version = "1.0.1"
dependencies = [ "bk_recomp_asset_expansion_pak:0.0.3", "font_plus_latin_1:1.0.0" ]
native_libraries = []

[inputs]
elf_path = "build/mod.elf"
mod_filename = "bardakoff_banjo"
func_reference_syms_file = "BanjoRecompSyms/bk.us.rev0.syms.toml"
data_reference_syms_files = [ "BanjoRecompSyms/bk.us.rev0.datasyms.toml" ]
additional_files = [ "thumb.png" ]
